# Generated by Django 5.2.1 on 2025-07-03 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for', models.DateField()),
                ('event_for', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='member_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=75, unique=True)),
                ('member_sedigh', models.PositiveIntegerField()),
                ('member_peresance', models.BinaryField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.form_data')),
            ],
        ),
    ]
