# Generated by Django 5.2.1 on 2025-07-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_member_data_member_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_data',
            name='member_name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
