# Generated by Django 5.2.1 on 2025-07-04 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_member_data_member_sedigh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_data',
            name='member_peresance',
        ),
    ]
