# Generated by Django 5.2.1 on 2025-07-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_member_data_member_peresance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_data',
            name='form_id',
        ),
    ]
