# Generated by Django 5.2.1 on 2025-07-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_member_data_form_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member_data',
            name='member_peresance',
            field=models.IntegerField(default=0),
        ),
    ]
