# Generated by Django 5.2.1 on 2025-07-05 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_member_data_member_peresance'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='form_data',
        ),
        migrations.RemoveField(
            model_name='member_data',
            name='member_peresance',
        ),
        migrations.AlterField(
            model_name='member_data',
            name='member_name',
            field=models.CharField(default='ناشناس', max_length=100),
        ),
        migrations.AlterField(
            model_name='member_data',
            name='member_sedigh',
            field=models.CharField(default='عمومی', max_length=100),
        ),
        migrations.AddField(
            model_name='presencerecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.member_data'),
        ),
    ]
