# Generated by Django 5.2.1 on 2025-07-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_form_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField()),
                ('latest_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
