# Generated by Django 5.2.1 on 2025-07-13 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admin_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='form_info',
            name='form_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
