# Generated by Django 5.2.1 on 2025-07-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_form_info_form_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form_info',
            name='form_date',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='presencerecord',
            name='date',
            field=models.DateField(),
        ),
    ]
