# Generated by Django 5.2.1 on 2025-07-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_form_info_form_date_alter_presencerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member_data',
            name='member_sedigh',
            field=models.IntegerField(default='عمومی', max_length=100),
        ),
        migrations.AlterField(
            model_name='presencerecord',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
